### ISSUE TITLE
Rename the project and detach from original repo

### ISSUE THREAD

**Issue by PhilKes** [PhilKes/Notally#26]
Since the original author of [Notally](https://github.com/OmGodse/Notally) seems inactive, I will detach the fork and create a new repository for the project and therefore also rename the project, probably to NotallyX.
This will also include the package structure

**Comment by CodeNomadHQ** [comment]
That sounds like a solid plan! It's your repo, so name it whatever you like, but maybe consider something like Nottify as an alternative.
