### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ippocratis** [PhilKes/Notally#7]
Thanks for adding issues so that users can discuss bugs/issues/features

I'd love to try the fork so please add releases

**Comment by CodeNomadHQ** [comment]
Here’s the [Link](https://github.com/CodeNomadHQ/Notally/releases/tag/Beta) to download the APK from my repo. It may have some bugs as the new features require further testing.

**Comment by PhilKes** [comment]
I'm currently trying to fix a few things with the new features, especially the auto-sort of checked tasks.
I'll probably make a release today

**Comment by PhilKes** [comment]
I just released the first SNAPSHOT version, but be aware are definetely bugs still, I will tackle some of them on the weekend
https://github.com/PhilKes/Notally/releases/tag/v6.0-SNAPSHOT
